export const TYPES = {
    SIGNING_IN: "SIGNING_IN",
    SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
    SIGN_IN_FAILURE: "SIGN_IN_FAILURE",

    SIGN_OUT: "SIGN_OUT",

    CHANGE_DELIVERY_DATE: "CHANGE_DELIVERY_DATE",

    FETCHING_DELIVERY_ITEMS: "FETCHING_DELIVERY_ITEMS",
    FETCH_DELIVERY_ITEMS_SUCCESS: "FETCH_DELIVERY_ITEMS_SUCCESS",
    FETCH_DELIVERY_ITEMS_FAILURE: "FETCH_DELIVERY_ITEMS_FAILURE",

    INVALIDATE_DELIVERY_ITEMS: "INVALIDATE_DELIVERY_ITEMS",

    SELECT_DELIVERY_ITEM: "SELECT_DELIVERY_ITEM",
};
